// answer1 for day 25 on xmas day 2015

/*

  x | y | result
~~~~~~~~~~~~~~~~~
  1 | 1 | 1

  1 | 2 | 2
  2 | 1 | 3
  
  1 | 3 | 4
  2 | 2 | 5
  3 | 1 | 6
  
  1 | 4 | 7
  2 | 3 | 8
  3 | 2 | 9
  4 | 1 | 10

*/

const calcCode = (prevCode) => {
  return (prevCode * 252533) % 33554393;
}

var x = 1;
var y = 2;
var idx = 1;
var category = 2;
var codes = [20151125];

const dest_x = 3075;
const dest_y = 2981;

console.log(' x | y | idx | code');
console.log('~~~~~~~~~~~~~~~~~~~~');
var done = false;
var start = new Date();
while (!done) {

  codes[idx] = calcCode(codes[idx - 1]);

  done = (x == dest_x && y == dest_y)
  if (done)
    console.log(` ${x} | ${y} | ${idx} | ${codes[idx]}`);

  // next iteration
  x++;
  if (x > category) {
    y = ++category;
    x = 1;
  } else {
    y--;
  }
  idx++;
}
console.log('took ' + (new Date() - start).valueOf() + 'ms')
/*

The first code is 20151125. After that, each code is generated by taking the 
previous one, multiplying it by 252533, and then keeping the remainder from
dividing that value by 33554393.

   |    1         2         3         4         5         6
---+---------+---------+---------+---------+---------+---------+
 1 | 20151125  18749137  17289845  30943339  10071777  33511524
 2 | 31916031  21629792  16929656   7726640  15514188   4041754
 3 | 16080970   8057251   1601130   7981243  11661866  16474243
 4 | 24592653  32451966  21345942   9380097  10600672  31527494
 5 |    77061  17552253  28094349   6899651   9250759  31663883
 6 | 33071741   6796745  25397450  24659492   1534922  27995004


*/

// Objective: Enter the code at row 2981, column 3075.


